### ISSUE TITLE
Unable to upload through React/ browser code

### ISSUE THREAD

**Issue by shelly-goel** [adobe/aem-upload#52]
Is this SDK not supported if we try to upload the asset through React application directly? We're uploading a file through browser and React application running picks up this file and upload to AEM with this SDK.

The application stops working on putting this code in React. Please suggest.

**Comment by shellygoelisobar** [comment]
On further analysis, I found that it was a CORS issue that the sdk wasn't working. Enabling CORS for *, the sdk now works but triggers initiateUpload request and other two requests but again errors out either 403 or CORS. Please suggest how to get rid of the 403/ CORS error even though AEM crossorigin is set to *

Another issue, I tried to make the 3 calls individually initiate and complete in server while presigned url request through React. I again get CORS error while uploading file to presigned url if the size is more than 100MB. Is there a size limit for file upload?

**Comment by mfrisbey** [comment]
@shellygoelisobar Thank you for the issue report!

> I again get CORS error while uploading file to presigned url if the size is more than 100MB

There are, indeed, limitations to the size. The `initiateUpload` response should include information about the maximum size a part can be. But manually performing uploads is out of scope for this module.

> the sdk now works but triggers initiateUpload request and other two requests but again errors out either 403 or CORS

We'll need some additional information in order to troubleshoot this. Will you please include the logs from both the `aem-upload` module and AEM itself? You can get aem-upload's logs by following the [instructions in the readme](https://github.com/adobe/aem-upload/blob/master/README.md#logging).

**Comment by shellygoelisobar** [comment]
1. But manually performing uploads is out of scope for this module.
[Shelly] There is a blob option and a file path option to provide the asset to the sdk. Won't the blob work with manual upload through react client? If not, what's the use case for blob?
2. Accessing AEM through client requires CORS enabled, Referrer Filter exclusion, and generation of CSRF token for each of the request to AEM - Are you saying this is not the intended purpose of this sdk and it's primary purpose is through server? If that's the case, is there anything in the roadmap to enhance this sdk for client side uploads as well?
3. How would you suggest the leveraging this sdk for client side upload.

**Comment by shelly-goel** [comment]
@mfrisbey  - Did you get a chance to look at my comments?

**Comment by mfrisbey** [comment]
@shelly-goel thank you for your patience here.

With #61, the documentation has been updated to clarify the `blob` option. For our use-case, we run the library on the same host/port as the rest of our website so there are no issues with CORS or CSRF.

That said, it's possible to use this library in a React application. However, due to the nature of browser security, AEM must be configured to allow HTTP requests from a different host when running in a browser:

* "Adobe Granite Cross-Origin Resource Sharing Policy" configuration (i.e. CORS). The minimum change I had to make to the default values of a new config was:
  * Specify either "Allowed Origins" or "Allowed Origins (Regexp)". Using a `*` will _not_ work when the "Supports Credentials" option is checked (AEM's logs will inform you of this).
  * Add one or more "Supported Headers"
* Extend the "Adobe Granite CSRF Filter" to allow requests from your browser.

_Modify these configurations at your own risk_; doing so opens AEM to potential security concerns. We'd recommend being familiar with the concepts of CORS and CSRF before making any final decisions about modifying these configurations in a production environment.

Closing the issue since it's not a problem with the library itself, nor are there any potential enhancements for changing this behavior from the library's perspective.

**Comment by shelly-goel** [comment]
@mfrisbey Thanks for your response, would need some more clarity here:
"For our use-case, we run the library on the same host/port as the rest of our website so there are no issues with CORS or CSRF."
Do you mean the react application is running within AEM code? How would we run the library on cloud and provide filePath from local, is there a possibility to provide an example to provide filePath for cloud instances (and not locally running AEM SDK)?
Is it possible to provide Azure SAS url to upload from?

**Comment by mfrisbey** [comment]
> Do you mean the react application is running within AEM code?

No, we use webpack to package `aem-upload` into javascript code that we install on AEM as a content package.

> How would we run the library on cloud and provide filePath from local

When running in a browser, we use the `blob` option instead of `filePath`. There aren't any examples of using `filePath` from a browser because, as far as I know, it's not possible for browsers to directly access paths on the local file system (for security reasons).

> Is it possible to provide Azure SAS url to upload from?

No, currently the library only supports file paths or blobs. It might be possible to do this, but we don't have any plans to extend the library to allow it.

**Comment by shelly-goel** [comment]
Thanks for the response @mfrisbey 
Can you please help me with a usecase for filePath please with AEM cloud?
Another question, does this only support upload of master asset, what if we have multiple adaptations of an asset, how do we upload them alongwith master asset?
